[package]
name = "molesim-renderer"
publish.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
flo_binding = "2.2.0"
flo_canvas = "0.3.1"
flo_draw = "0.3.1"
futures = "0.3.30"
futures-core = "0.3.30"
molesim-core = { path = "../core" }
