[package]
name = "molesim-renderer"
publish.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
flo_canvas = "0.3.1"
flo_draw = "0.3.1"
molesim-core = { path = "../core" }
