[package]
name = "molesim-gdext"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
molesim-core = { path = "../core" }
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
